language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-dev.txt
# command to run tests
script:
  - make cov
after_success:
  - codecov
branches:
  only:
  - master
