language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip3 install pytest pytest-cov
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest --cov=seriesbr
branches:
  only:
  - master
