#!/bin/bash

for file in *.org; do
    if [ "$file" != "README.org" ]; then
        rst="${file%.*}.rst"
        pandoc -f org -t rst -o "$rst" "$file"
        sed -i -e '/^\.\. \|image/ s#imgs#../../../imgs#' -e 's/ TOC$//' "$rst"
        mv "$rst" docs/source/demos
    fi
done
