name: Code quality

on: [push]

jobs:
  build:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Test and generate code coverage report in XML
        run: poetry run pytest --cov=seriesbr --cov-report=xml

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
